export interface Question {
  id: number
  text: string
  options: string[]
  answer: number // 0-based index
  explanation?: string
}

export const questions: Question[] = [
  {
    id: 1,
    text: "Which of the following is an essential characteristic of cloud computing?",
    options: [
      "Measured service",
      "On-demand self-service",
      "Broad network access",
      "All of the above",
    ],
    answer: 3,
  },
  {
    id: 2,
    text: "Which of the following is NOT a characteristic of cloud computing as defined by NIST?",
    options: [
      "Measured service",
      "On-demand self-service",
      "Local resource ownership",
      "Rapid elasticity",
    ],
    answer: 2,
  },
  {
    id: 3,
    text: "What is the correct sequence for data disclosure in a cloud environment?",
    options: [
      "Data collection, Data processing, Data transfer, Data storage, Data deletion",
      "Data collection, Data transfer, Data storage, Data processing, Data deletion",
      "Data storage, Data collection, Data processing, Data transfer, Data deletion",
      "Data processing, Data collection, Data transfer, Data storage, Data deletion",
    ],
    answer: 0,
  },
  {
    id: 4,
    text: "Which of the following is an example of a law that may require data to be stored within a specific jurisdiction?",
    options: [
      "Payment Card Industry Data Security Standard (PCI DSS)",
      "Sarbanes-Oxley Act (SOX)",
      "Data Protection Act",
      "Health Insurance Portability and Accountability Act (HIPAA)",
    ],
    answer: 2,
  },
  {
    id: 5,
    text: "What is the main responsibility of the cloud customer in a Software as a Service (SaaS) model?",
    options: [
      "Managing the underlying infrastructure",
      " Installing and managing the application",
      " Configuring the application",
      " Maintaining the physical security of the data center",
    ],
    answer: 2,
  },
  {
    id: 6,
    text: "Which security concept is BEST described as ensuring that data is not modified without authorization?",
    options: [
      "Confidentiality",
      "Integrity",
      "Availability",
      "Authentication",
    ],
    answer: 1,
  },
  {
    id: 7,
    text: "In which cloud deployment model is the cloud infrastructure shared by several organizations with common concerns?",
    options: [
      "Private cloud",
      "Public cloud",
      "Community cloud",
      "Hybrid cloud",
    ],
    answer: 2,
  },
  {
    id: 8,
    text: "What type of hypervisor runs directly on the physical server hardware without a host operating system?",
    options: [
      "Type 1 hypervisor",
      "Type 2 hypervisor",
      "Bare metal hypervisor",
      "Hosted hypervisor",
    ],
    answer: 2,
  },
  {
    id: 9,
    text: "Which of the following is an example of multi-jurisdiction data taxation?",
    options: [
      "Tax based on where the data is physically stored",
      "Tax based on where the data controller is located",
      "Tax based on where the data subject is located",
      "Tax based on where the data is processed",
    ],
    answer: 0,
  },
  {
    id: 10,
    text: "Which cloud service model provides the MOST control over the underlying infrastructure?",
    options: [
      "Software as a Service (SaaS)",
      "Platform as a Service (PaaS)",
      "Infrastructure as a Service (IaaS)",
      "Function as a Service (FaaS)",
    ],
    answer: 2,
  },
  {
    id: 11,
    text: "Which virtualization layer component is responsible for creating and managing virtual machines?",
    options: [
      "Virtual machine monitor (VMM)",
      "Hypervisor",
      "Host OS",
      "Virtual switch",
    ],
    answer: 1,
  },
  {
    id: 12,
    text: "What is a primary security concern with virtualization?",
    options: [
      "VM escape",
      "VM sprawl",
      "Loss of SLAs",
      "All of the above",
    ],
    answer: 3,
  },
  {
    id: 13,
    text: "Which protocol is commonly used for secure communication to a cloud service?",
    options: [
      "HTTP",
      "FTP",
      "TLS/SSL",
      "SMTP",
    ],
    answer: 2,
  },
  {
    id: 14,
    text: "What is the purpose of a hypervisor in cloud computing?",
    options: [
      "To provide network connectivity",
      "To manage physical hardware resources",
      "To create and manage virtual machines",
      "To provide storage services",
    ],
    answer: 2,
  },
  {
    id: 15,
    text: "Which cloud deployment model offers the GREATEST isolation?",
    options: [
      "Public cloud",
      "Private cloud",
      "Community cloud",
      "Hybrid cloud",
    ],
    answer: 1,
  },
  {
    id: 16,
    text: "What is VM sprawl?",
    options: [
      "VM moving between hosts",
      "Uncontrolled proliferation of VMs",
      "VM running slowly",
      "VM crashing",
    ],
    answer: 1,
  },
  {
    id: 17,
    text: "Which of the following is a BEST practice for securing virtual machines?",
    options: [
      "Disable VM snapshot functionality",
      "Use dedicated VLANs for VMs",
      "Allow unlimited VM resource allocation",
      "Disable hyperthreading",
    ],
    answer: 1,
  },
  {
    id: 18,
    text: "What type of attack involves an attacker gaining access to a VM and then moving to the host or other VMs?",
    options: [
      "VM escape",
      "Denial of service",
      "SQL injection",
      "Cross-site scripting",
    ],
    answer: 0,
  },
  {
    id: 19,
    text: "Which security concept ensures that only authorized individuals can access data?",
    options: [
      "Confidentiality",
      "Integrity",
      "Availability",
      "Non-repudiation",
    ],
    answer: 0,
  },
  {
    id: 20,
    text: "What is a key consideration when selecting a cloud service provider?",
    options: [
      "Location of data centers",
      "Compliance certifications",
      "Data portability",
      "All of the above",
    ],
    answer: 3,
  },
  {
    id: 21,
    text: "Which of the following is a shared responsibility in a Platform as a Service (PaaS) model?",
    options: [
      "Physical infrastructure",
      "Operating system",
      "Application code",
      "Physical network",
    ],
    answer: 2,
  },
  {
    id: 22,
    text: "What is the purpose of data classification in a cloud environment?",
    options: [
      "To increase storage costs",
      "To determine appropriate security controls",
      "To slow down data access",
      "To complicate compliance",
    ],
    answer: 1,
  },
  {
    id: 23,
    text: "Which encryption method is BEST suited for data at rest in the cloud?",
    options: [
      "Link encryption",
      "End-to-end encryption",
      "Storage encryption",
      "Email encryption",
    ],
    answer: 2,
  },
  {
    id: 24,
    text: "What is a key characteristic of a community cloud?",
    options: [
      "Available to the general public",
      "Shared by organizations with common interests",
      "Owned by a single organization",
      "Combines public and private clouds",
    ],
    answer: 1,
  },
  {
    id: 25,
    text: "Which of the following is MOST important when conducting a cloud risk assessment?",
    options: [
      "Vendor lock-in",
      "Data location",
      "Cost of services",
      "Brand reputation",
    ],
    answer: 1,
  },
  {
    id: 26,
    text: "What is the purpose of a Service Level Agreement (SLA) in cloud computing?",
    options: [
      "To define security controls",
      "To specify performance and availability commitments",
      "To regulate data ownership",
      "To manage VM sprawl",
    ],
    answer: 1,
  },
  {
    id: 27,
    text: "Which of the following should be included in a cloud incident response plan?",
    options: [
      "Roles and responsibilities",
      "Communication procedures",
      "Escalation paths",
      "All of the above",
    ],
    answer: 3,
  },
  {
    id: 28,
    text: "What is a primary concern when using multi-tenancy in a cloud environment?",
    options: [
      "Cost optimization",
      "Data isolation",
      "Performance degradation",
      "Vendor lock-in",
    ],
    answer: 1,
  },
  {
    id: 29,
    text: "Which of the following is a BEST practice for identity and access management in the cloud?",
    options: [
      "Use shared accounts",
      "Implement least privilege",
      "Disable logging",
      "Allow all traffic by default",
    ],
    answer: 1,
  },
  {
    id: 30,
    text: "What type of attack aims to overwhelm cloud resources to make them unavailable?",
    options: [
      "VM escape",
      "Denial of service",
      "SQL injection",
      "Cross-site scripting",
    ],
    answer: 1,
  },
  {
    id: 31,
    text: "Which encryption technique allows computations to be performed on encrypted data?",
    options: [
      "AES encryption",
      "Homomorphic encryption",
      "Hashing",
      "Tokenization",
    ],
    answer: 1,
  },
  {
    id: 32,
    text: "What is the main benefit of using a virtual private cloud (VPC)?",
    options: [
      "Lower cost",
      "Improved isolation and security",
      "Faster performance",
      " Easier management",
    ],
    answer: 1,
  },
  {
    id: 33,
    text: "Which of the following is MOST important when outsourcing to a cloud service provider?",
    options: [
      "Location of data centers",
      "Due diligence and vendor assessment",
      "Brand recognition",
      "Marketing materials",
    ],
    answer: 1,
  },
  {
    id: 34,
    text: "What is a key component of a cloud security architecture?",
    options: [
      "Single point of failure",
      "Defense in depth",
      "Maximum permissions",
      "Open network access",
    ],
    answer: 1,
  },
  {
    id: 35,
    text: "Which of the following helps ensure data confidentiality in transit?",
    options: [
      "HTTP",
      "FTP",
      "TLS/SSL",
      "SMTP",
    ],
    answer: 2,
  },
  {
    id: 36,
    text: "What is a primary purpose of network segmentation in a cloud environment?",
    options: [
      "To increase bandwidth",
      "To isolate workloads and control access",
      "To reduce costs",
      "To simplify management",
    ],
    answer: 1,
  },
  {
    id: 37,
    text: "Which security control is MOST effective against insider threats?",
    options: [
      "Encryption",
      "Least privilege and monitoring",
      "Firewall",
      "Antivirus",
    ],
    answer: 1,
  },
  {
    id: 38,
    text: "What is a key consideration when implementing DLP in the cloud?",
    options: [
      "Cost only",
      "Data in transit, at rest, and in use",
      "Network speed only",
      "Storage capacity only",
    ],
    answer: 1,
  },
  {
    id: 39,
    text: "Which of the following is a benefit of cloud-native security?",
    options: [
      "Increased complexity",
      "Automated scaling of security controls",
      "Higher operational overhead",
      "Manual security management",
    ],
    answer: 1,
  },
  {
    id: 40,
    text: "What is the PRIMARY advantage of SIEM in a cloud environment?",
    options: [
      "Reduced cost",
      "Centralized log management and correlation",
      "Faster network",
      "Larger storage",
    ],
    answer: 1,
  },
  {
    id: 41,
    text: "Which of the following is MOST important when reviewing a CSP's security controls?",
    options: [
      "Marketing materials",
      "Third-party audit reports",
      "Competitor analysis",
      "Price lists",
    ],
    answer: 1,
  },
  {
    id: 42,
    text: "What is a key characteristic of DevSecOps?",
    options: [
      "Security is added at the end",
      "Security is integrated throughout the development lifecycle",
      "Security is only the responsibility of the security team",
      "Security is optional",
    ],
    answer: 1,
  },
  {
    id: 43,
    text: "Which of the following is a container security best practice?",
    options: [
      "Use privileged containers",
      "Scan containers for vulnerabilities",
      "Disable container orchestration",
      "Allow all container network traffic",
    ],
    answer: 1,
  },
  {
    id: 44,
    text: "What is a key difference between VMs and containers?",
    options: [
      "Containers provide stronger isolation",
      "Containers share the host OS kernel",
      "VMs are more lightweight",
      "VMs cannot be automated",
    ],
    answer: 1,
  },
  {
    id: 45,
    text: "Which of the following is MOST relevant to a cloud security assessment?",
    options: [
      "Color scheme of the website",
      "Network diagrams and architecture",
      "Employee count",
      "Office location",
    ],
    answer: 1,
  },
  {
    id: 46,
    text: "What is the purpose of CASB in a cloud environment?",
    options: [
      "To manage container security",
      "To provide visibility and control over cloud applications",
      "To speed up cloud deployment",
      "To reduce cloud costs",
    ],
    answer: 1,
  },
  {
    id: 47,
    text: "Which security control is appropriate for protecting data in a multi-tenant cloud environment?",
    options: [
      "Shared encryption keys",
      "Tenant-specific encryption keys",
      "No encryption",
      "Single tenant per cluster",
    ],
    answer: 1,
  },
  {
    id: 48,
    text: "What is a key consideration for API security in cloud services?",
    options: [
      "Rate limiting and authentication",
      "Using HTTP instead of HTTPS",
      "Disabling logging",
      "Allowing anonymous access",
    ],
    answer: 0,
  },
  {
    id: 49,
    text: "Which of the following is a BEST practice for securing serverless functions?",
    options: [
      "Use excessive permissions",
      "Apply least privilege to function permissions",
      "Disable logging",
      "Allow public access by default",
    ],
    answer: 1,
  },
  {
    id: 50,
    text: "What is a key characteristic of a microsegmentation security strategy?",
    options: [
      "Flat network architecture",
      "Fine-grained network isolation",
      "Single security zone",
      "No network controls",
    ],
    answer: 1,
  },
  {
    id: 51,
    text: "Which standard provides a framework for information security management?",
    options: [
      "ISO 27001",
      "PCI DSS",
      "HIPAA",
      "SOX",
    ],
    answer: 0,
  },
  {
    id: 52,
    text: "What is the purpose of a business continuity plan in a cloud environment?",
    options: [
      "To define cloud costs",
      "To ensure availability during disruptions",
      "To manage employee schedules",
      "To design network architecture",
    ],
    answer: 1,
  },
  {
    id: 53,
    text: "Which of the following is MOST important for cloud data portability?",
    options: [
      "Using proprietary formats",
      "Using standard data formats and APIs",
      "Limiting data export",
      "Using a single cloud provider exclusively",
    ],
    answer: 1,
  },
  {
    id: 54,
    text: "What is a key benefit of security automation in the cloud?",
    options: [
      "Increased manual work",
      "Faster incident detection and response",
      "Higher operational costs",
      "More security staff required",
    ],
    answer: 1,
  },
  {
    id: 55,
    text: "Which of the following is a shared responsibility in an IaaS model?",
    options: [
      "Physical security",
      "Network security",
      "Data security",
      "Physical infrastructure",
    ],
    answer: 2,
  },
  {
    id: 56,
    text: "What is a key consideration when implementing IAM in a cloud environment?",
    options: [
      "Using weak passwords",
      "Implementing MFA",
      "Disabling audit logs",
      "Allowing shared accounts",
    ],
    answer: 1,
  },
  {
    id: 57,
    text: "Which cloud service model is MOST suitable for development and testing environments?",
    options: [
      "SaaS",
      "PaaS",
      "IaaS",
      "FaaS",
    ],
    answer: 2,
  },
  {
    id: 58,
    text: "What is a key characteristic of a zero-trust security model?",
    options: [
      "Trust internal network by default",
      "Never trust, always verify",
      "Trust based on location",
      "Single authentication point",
    ],
    answer: 1,
  },
  {
    id: 59,
    text: "Which of the following is a consideration for cloud governance?",
    options: [
      "Shadow IT management",
      "Cost monitoring",
      "Compliance monitoring",
      "All of the above",
    ],
    answer: 3,
  },
  {
    id: 60,
    text: "What is the purpose of a cloud security alliance?",
    options: [
      "To increase cloud costs",
      "To promote best practices and security standards",
      "To limit cloud adoption",
      "To reduce vendor options",
    ],
    answer: 1,
  },
  {
    id: 61,
    text: "Which of the following is MOST important when creating a cloud security policy?",
    options: [
      "Making it complex",
      "Aligning it with business objectives",
      "Keeping it secret",
      "Updating it rarely",
    ],
    answer: 1,
  },
  {
    id: 62,
    text: "What is a key component of cloud security monitoring?",
    options: [
      "Single log source",
      "Centralized log analysis",
      "No alerting",
      "Manual review only",
    ],
    answer: 1,
  },
  {
    id: 63,
    text: "Which encryption method is appropriate for data at rest?",
    options: [
      "TLS",
      "IPsec",
      "AES",
      "SSH",
    ],
    answer: 2,
  },
  {
    id: 64,
    text: "What is a key consideration in cloud incident management?",
    options: [
      "Delaying notification",
      "Coordinating with the CSP",
      "Hiding the incident",
      "Ignoring compliance requirements",
    ],
    answer: 1,
  },
  {
    id: 65,
    text: "Which of the following is a benefit of using MFA for cloud access?",
    options: [
      "Reduced security",
      "Enhanced authentication security",
      "Slower access",
      "Higher costs only",
    ],
    answer: 1,
  },
  {
    id: 66,
    text: "What is a key principle of least privilege in cloud security?",
    options: [
      "Give maximum permissions",
      "Grant minimum permissions necessary",
      "Share permissions freely",
      "Disable access controls",
    ],
    answer: 1,
  },
  {
    id: 67,
    text: "Which framework is specifically designed for cloud security?",
    options: [
      "COBIT",
      "CSA CCM",
      "NIST CSF",
      "ISO 22301",
    ],
    answer: 1,
  },
  {
    id: 68,
    text: "What is the PRIMARY purpose of cloud security certification?",
    options: [
      "Marketing",
      "Demonstrating compliance and security posture",
      "Reducing costs",
      "Increasing sales",
    ],
    answer: 1,
  },
  {
    id: 69,
    text: "Which of the following is a consideration for cloud database security?",
    options: [
      "Disabling encryption",
      "Implementing access controls and encryption",
      "Allowing unlimited queries",
      "Using default credentials",
    ],
    answer: 1,
  },
  {
    id: 70,
    text: "What is a key difference between cloud backup and cloud disaster recovery?",
    options: [
      "Backup is for data restoration; DR is for business continuity",
      "They are the same thing",
      "Backup is faster than DR",
      "DR is less important",
    ],
    answer: 0,
  },
  {
    id: 71,
    text: "Which of the following is MOST important for secure cloud configuration?",
    options: [
      "Using default settings",
      "Regular configuration reviews and hardening",
      "Disabling security features",
      "Allowing all traffic",
    ],
    answer: 1,
  },
  {
    id: 72,
    text: "What is a key characteristic of a botnet?",
    options: [
      "Legitimate traffic",
      "Compromised devices under attacker control",
      "Secure network",
      "Authorized access",
    ],
    answer: 1,
  },
  {
    id: 73,
    text: "Which of the following is a social engineering attack?",
    options: [
      "DDoS",
      "Phishing",
      "SQL injection",
      "Cross-site scripting",
    ],
    answer: 1,
  },
  {
    id: 74,
    text: "What is the BEST defense against XSS attacks?",
    options: [
      "Disabling JavaScript",
      "Input validation and output encoding",
      "Using HTTP only",
      "Allowing all input",
    ],
    answer: 1,
  },
  {
    id: 75,
    text: "Which attack involves injecting malicious code into a database query?",
    options: [
      "XSS",
      "CSRF",
      "SQL injection",
      "DDoS",
    ],
    answer: 2,
  },
  {
    id: 76,
    text: "What is the purpose of WAF in a cloud environment?",
    options: [
      "To protect against web application attacks",
      "To manage VMs",
      "To provide storage",
      "To monitor network speed",
    ],
    answer: 0,
  },
  {
    id: 77,
    text: "Which of the following is a DNS security concern?",
    options: [
      "DNS amplification attacks",
      "DNS cache poisoning",
      "DNS tunneling",
      "All of the above",
    ],
    answer: 3,
  },
  {
    id: 78,
    text: "What is the purpose of honeypot in a security architecture?",
    options: [
      "To attract and detect attackers",
      "To speed up production systems",
      "To reduce costs",
      "To simplify management",
    ],
    answer: 0,
  },
  {
    id: 79,
    text: "Which of the following is a key component of a security awareness program?",
    options: [
      "Technical training only",
      "Phishing simulations and education",
      "Marketing materials",
      "HR compliance only",
    ],
    answer: 1,
  },
  {
    id: 80,
    text: "What is a key consideration in cloud vulnerability management?",
    options: [
      "Ignoring vulnerabilities",
      "Regular scanning and patching",
      "Disabling security updates",
      "Allowing all traffic",
    ],
    answer: 1,
  },
  {
    id: 81,
    text: "Which of the following is a secure method for storing passwords?",
    options: [
      "Plain text",
      "Hashing with salt",
      "Reversible encryption",
      "Base64 encoding",
    ],
    answer: 1,
  },
  {
    id: 82,
    text: "What is the purpose of a security information and event management (SIEM) system?",
    options: [
      "To speed up the network",
      "To collect and analyze security events",
      "To reduce storage costs",
      "To manage VMs",
    ],
    answer: 1,
  },
  {
    id: 83,
    text: "Which of the following is MOST important for cloud availability?",
    options: [
      "Single point of failure",
      "Redundancy and failover",
      "Disabling backups",
      "Limiting scalability",
    ],
    answer: 1,
  },
  {
    id: 84,
    text: "What is a key characteristic of a strong password policy?",
    options: [
      "Short passwords",
      "Complexity requirements and regular rotation",
      "No requirements",
      "Single character passwords",
    ],
    answer: 1,
  },
  {
    id: 85,
    text: "Which of the following is a secure cloud networking practice?",
    options: [
      "Using default VPC settings",
      "Implementing network segmentation and firewalls",
      "Allowing all traffic",
      "Disabling encryption",
    ],
    answer: 1,
  },
  {
    id: 86,
    text: "What is the purpose of a CSP's security attestations?",
    options: [
      "Marketing only",
      "Demonstrating security controls to customers",
      "Increasing prices",
      "Reducing compliance",
    ],
    answer: 1,
  },
  {
    id: 87,
    text: "Which of the following is a key principle of data residency compliance?",
    options: [
      "Ignoring data location",
      "Ensuring data is stored in compliant jurisdictions",
      "Storing data anywhere",
      "Deleting compliance requirements",
    ],
    answer: 1,
  },
  {
    id: 88,
    text: "What is a key consideration when using third-party cloud services?",
    options: [
      "Vendor lock-in only",
      "Security and compliance implications",
      "Cost only",
      "Speed only",
    ],
    answer: 1,
  },
  {
    id: 89,
    text: "Which of the following is a secure method for API authentication?",
    options: [
      "Basic authentication",
      "API keys and OAuth",
      "No authentication",
      "Shared credentials",
    ],
    answer: 1,
  },
  {
    id: 90,
    text: "What is a key characteristic of Confidential Computing?",
    options: [
      "Data encrypted only at rest",
      "Data encrypted during processing",
      "Data stored in plain text",
      "No encryption used",
    ],
    answer: 1,
  },
  {
    id: 91,
    text: "Which of the following is a benefit of cloud elasticity?",
    options: [
      "Fixed costs",
      "Pay-as-you-go growth",
      "Limited scaling",
      "Slow deployment",
    ],
    answer: 1,
  },
  {
    id: 92,
    text: "What is a key component of a cloud security strategy?",
    options: [
      "Ignoring risks",
      "Risk assessment and mitigation",
      "Maximum permissions",
      "No monitoring",
    ],
    answer: 1,
  },
  {
    id: 93,
    text: "Which of the following is a consideration for cloud cost security?",
    options: [
      "Unlimited spending",
      "Monitoring and controlling cloud spend",
      "No cost controls",
      "Fixed pricing always",
    ],
    answer: 1,
  },
  {
    id: 94,
    text: "What is the purpose of a cloud security metrics dashboard?",
    options: [
      "To hide security posture",
      "To provide visibility into security controls",
      "To slow down operations",
      "To increase complexity",
    ],
    answer: 1,
  },
  {
    id: 95,
    text: "Which of the following is MOST important for secure cloud migrations?",
    options: [
      "No planning",
      "Security validation at each phase",
      "Migrating everything at once",
      "Ignoring compliance",
    ],
    answer: 1,
  },
  {
    id: 96,
    text: "What is a key consideration in cloud key management?",
    options: [
      "Sharing keys freely",
      "Secure key storage and rotation",
      "No key management",
      "Keys in plain text",
    ],
    answer: 1,
  },
  {
    id: 97,
    text: "Which of the following is a secure container orchestration practice?",
    options: [
      "Disabling RBAC",
      "Using RBAC and network policies",
      "Allowing all container operations",
      "No authentication",
    ],
    answer: 1,
  },
  {
    id: 98,
    text: "What is a key characteristic of FaaS security?",
    options: [
      "No permission controls",
      "Function-level permission controls",
      "Unlimited function execution",
      "No logging",
    ],
    answer: 1,
  },
  {
    id: 99,
    text: "Which of the following is a consideration for cloud supply chain security?",
    options: [
      "Ignoring third-party components",
      "Assessing third-party security posture",
      "No vendor management",
      "Using unverified components",
    ],
    answer: 1,
  },
  {
    id: 100,
    text: "What is a key principle of cloud security logging?",
    options: [
      "Logging everything without analysis",
      "Comprehensive logging with regular review",
      "No logging",
      "Deleting logs regularly",
    ],
    answer: 1,
  },
]
